# Generated by Django 2.0.5 on 2018-05-16 11:54

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=256)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_contact', models.BooleanField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=32)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='contacts.Bundle')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contacts.Bundle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=256)),
                ('clones_shareable', models.BooleanField()),
                ('clones_editable', models.BooleanField()),
                ('can_share', models.BooleanField()),
                ('can_edit', models.BooleanField()),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='contacts.Bundle')),
                ('cloned_from', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='contacts.Ticket')),
                ('cloned_root', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='all_clones', to='contacts.Ticket')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
