# Generated by Django 2.0.5 on 2018-05-17 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='contacts.Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cloned_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='all_clones', to='contacts.Ticket'),
        ),
    ]
