# Generated by Django 2.0.5 on 2018-05-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20180517_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='inner_bundles',
            field=models.ManyToManyField(related_name='in_bundles', to='contacts.Bundle'),
        ),
    ]
