# Generated by Django 2.0.5 on 2018-05-21 23:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_bundle_inner_bundles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='contact',
        ),
        migrations.AddField(
            model_name='bundle',
            name='information',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='inner_bundles',
            field=models.ManyToManyField(blank=True, related_name='in_bundles', to='contacts.Bundle'),
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
